default:
  image: busybox

stages:
  - build
  - deploy

.common/runners/dev:
    tags:
        - dodo
        - dev
    variables:
        CLUSTER: dev

.common/dind_service:
    services:
        - docker:dind
    variables:
        DOCKER_HOST: tcp://docker:2375/
        DOCKER_DRIVER: overlay
        DOCKER_TLS_CERTDIR: ""
        GIT_SSL_NO_VERIFY: "1"
    before_script:
        - docker info
    after_script:
        - docker images

build/dotnet-dev-image:
  stage: build
  image: docker
  extends:
    - .common/runners/dev
    - .common/dind_service
  script:
    - cd .devcontainer
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - |
      DOCKER_BUILDKIT=1 docker build \
        --progress=plain \
        --build-arg BUILDKIT_INLINE_CACHE=1 \
        --cache-from $CI_REGISTRY_IMAGE/dotnetdev:latest-cache \
        --tag $CI_REGISTRY_IMAGE/dotnetdev:latest-cache
        .
    - docker push $CI_REGISTRY_IMAGE/dotnetdev:latest-cache

deploy/function:
  stage: deploy
  image: $CI_REGISTRY_IMAGE/dotnetdev
  script:
    - dotnet restore
  dependencies:
    - build/dotnet-dev-image