version: "3.7"
services:
  vscode:
    build:
      context: .
      dockerfile: Dockerfile
    command: bash -c 'echo Container started ; while sleep 1; do :; done'
    working_dir: /workspace
    volumes:
      - ../:/workspace
    ports:
      - "7071:7071"
  prom1:
    image: prom/prometheus:v2.16.0
    volumes:
      - "./docker-compose/prom1-prometheus.yml:/etc/prometheus/prometheus.yml"
    ports:
      - "9090:9090"
  prom2:
    image: prom/prometheus:v2.16.0
    volumes:
      - "./docker-compose/prom2-prometheus.yml:/etc/prometheus/prometheus.yml"
    ports:
      - "9091:9090"
  grafana:
    image: grafana/grafana:master
    volumes:
      - "./grafana-data:/var/lib/grafana"
    ports:
      - "3000:3000"
  node-exporter:
    image: prom/node-exporter:latest
    ports:
      - "9100:9100"