name: Deploy

on:
  workflow_dispatch:

env:
  DOTNET_VERSION: '3.1'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:

    - name: 'Checkout GitHub Action'
      uses: actions/checkout@master

    - name: Setup DotNet ${{ env.DOTNET_VERSION }} Environment
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

    - name: 'Resolve dependencies and build project'
      run: dotnet build --configuration Release --output ./output

    - name: 'Publish project to ld'
      env:
        SP_NAME: SP_ADX_LD
        FUNCTIONAPP_NAME: ld-prometheus-adx
      run: |
        ./.github/scripts/01-az-login.sh ${SP_NAME}
        func azure functionapp publish ${FUNCTIONAPP_NAME} --publish-local-settings --overwrite-settings
