name: Deploy

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'LD|EU2|WE'
        required: true
        default: 'LD'

env:
  DOTNET_VERSION: '3.1'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:

    - name: 'Checkout GitHub Action'
      uses: actions/checkout@master

    - name: Setup DotNet ${{ env.DOTNET_VERSION }} Environment
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

    - name: 'Install azure-functions-core-tools-3'
      run: sudo apt-get -y install azure-functions-core-tools-3

    - name: 'Publish project to ${{ github.event.inputs.cluster }}'
      if: 
      env:
        SP_NAME: ${{ secrets[format('SP_{0}', github.event.inputs.cluster)] }}
        APPLICATION_SETTINGS: ${{ secrets[format('AS_{0}', github.event.inputs.cluster)] }}
        FUNCTIONAPP_NAME: ${{ secrets[format('{0}-prometheus-adx', github.event.inputs.cluster)] }}
      run: |
        ./.github/scripts/01-az-login.sh SP_NAME
        echo "${APPLICATION_SETTINGS}" > local.settings.json
        func azure functionapp publish $(echo "${FUNCTIONAPP_NAME}" | awk '{print tolower($0)}') --publish-local-settings --overwrite-settings
