name: Build and test

on:
  push:
    branches:
      - "*"
      - "!master"

jobs:
  build:
    name: Build and test
    runs-on: ubuntu-18.04
    steps:

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build runtime image
        uses: docker/build-push-action@v2
        with:
          push: false
          context: .
          file: .devcontainer/Dockerfile
          tags: afruntime:latest

